// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/cmd_job.got
// DO NOT EDIT!
package template

import (
	"bytes"
	"fmt"
)

func FromCmdJob(name, jobCmd, jobFunctions string, buffer *bytes.Buffer) {
	buffer.WriteString(fmt.Sprintf(`
package jobs

import (
	"%s/jobs/config"
	"github.com/urfave/cli/v2"
	"github.com/weblazy/easy/closes"
)

// Job cmd 任务相关
var Cmd = &cli.Command{
	Name:    "job",
	Aliases: []string{"j"},
	Usage:   "job",
	Subcommands: []*cli.Command{
		%s
	},
}

%s
`, name, jobCmd, jobFunctions))
}
