// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/cmd_api.got
// DO NOT EDIT!
package template

import (
	"bytes"
	"fmt"
)

func FromCmdApi(homePath string, buffer *bytes.Buffer) {
	buffer.WriteString(fmt.Sprintf(`
package cmd

import (
	"%s/routes"
	conf "%s/config"

	"github.com/gin-contrib/gzip"
	"github.com/gin-gonic/gin"
	"github.com/weblazy/easy/utils/conf/viper"
	"github.com/sunmi-OS/gocore/v2/utils"
	"github.com/weblazy/easy/utils/closes"
	"github.com/urfave/cli/v2"
	"github.com/weblazy/easy/utils/http/http_server"
	"github.com/weblazy/easy/utils/http/http_server/config"
)

var Cmd = &cli.Command{
	Name:    "api",
	Aliases: []string{"a"},
	Usage:   "api start",
	Subcommands: []*cli.Command{
		{
			Name:   "start",
			Usage:  "开启运行api服务",
			Action: Run,
		},
	},
}

func Run(c *cli.Context) error {
	defer closes.Close()

	cmd.InitConf()
	cmd.InitDB()
	cmd.InitCache()
	
	if utils.IsRelease() {
		gin.SetMode(gin.ReleaseMode)
	}

	cfg := config.DefaultConfig()
	s, err := http_server.NewHttpServer(cfg)
	if err != nil {
		return err
	}
	// 注册路由
	routes.Routes(r)

	err := s.Start()
	if err != nil {
		return err
	}
	return nil
}`,homePath,homePath))

}
