// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/err_code.got
// DO NOT EDIT!
package template

import "bytes"

func FromErrCode(buffer *bytes.Buffer) {
	buffer.WriteString(`
package errcode

import (
	"github.com/weblazy/easy/code_err"
	"gorm.io/gorm"
)

var (
	ErrorNotFound = code_err.NewCodeErr(50001, gorm.ErrRecordNotFound.Error())
)`)

}
