// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/api.got
// DO NOT EDIT!
package template

import (
	"bytes"
	"fmt"
)

func FromHandler(homePath,homedir,handlerName string , comments []string, functions []string,  buffer *bytes.Buffer) {

	for k1, v1 := range functions {
		buffer.WriteString(fmt.Sprintf(`
package %s

import (
	"%s/def"
	"%s/logic/%s"

	"github.com/gin-gonic/gin"
	"github.com/weblazy/easy/utils/http/http_server/service"
)
    // %s
	func %s(g *gin.Context) {
		 svcCtx := service.NewServiceContext(g)
		 req := new(def.%sRequest)
		 err := svcCtx.BindValidator(req)
		 if err != nil {
			svcCtx.Error(err)
			return
		 }
		resp, code, err := %s.%s(svcCtx, req)
		if err != nil {
			svcCtx.ErrorCodeMsg(code, err.Error())
			return
		}
		svcCtx.Success(resp)
	}
`,handlerName,homePath,homePath,handlerName, comments[k1],v1,v1,handlerName,v1))
	}

}
