// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/api.got
// DO NOT EDIT!
package template

import (
	"bytes"
	"fmt"
)

func FromHttpLogic(homePath, handlerName, funcName, comment string, buffer *bytes.Buffer) {

	buffer.WriteString(fmt.Sprintf(`
package %s

import (
	"%s/def"
	"github.com/weblazy/easy/code_err"

)

    // %s
	func %s(svcCtx *service.ServiceContext, req *def.%sRequest) *code_err.CodeErr{
		return nil
	}
`, handlerName, homePath, comment, funcName, funcName))

}

func FromRpcLogic(handlerName, funcName, comment string, buffer *bytes.Buffer) {
	buffer.WriteString(fmt.Sprintf(`
package %s_logic

import (
	"github.com/weblazy/easy/code_err"

)
	type %sCtx struct {
		*code_err.SvcContext
		Req *user.%sRequest
		Res *user.%sResponse
	}
    // %s
	func %s(ctx *%sCtx) *code_err.CodeErr{
		return nil
	}
`, handlerName, funcName, funcName, funcName, comment, funcName, funcName))

}
