// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/main.got
// DO NOT EDIT!
package template

import (
	"bytes"
	"fmt"
)

func FromMain(projectName string, cmdList []string, pkgList string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package main

import (
	"os"`)
	buffer.WriteString(fmt.Sprintf("%s\n\"%s/common\"", pkgList, projectName))
	buffer.WriteString(
		`
	"github.com/weblazy/easy/elog"
	"github.com/weblazy/easy/print"
	"github.com/urfave/cli/v2"
)

func main() {
	// 打印Banner
	print.PrintBanner(common.ProjectName)
	// 配置cli参数
	cliApp := cli.NewApp()
	cliApp.Name = common.ProjectName
	cliApp.Version = common.ProjectVersion

	// 指定命令运行的函数
	cliApp.Commands = []*cli.Command{
        `)
	for _, cmd := range cmdList {
		buffer.WriteString(cmd)
	}
	buffer.WriteString(`
	}

	// 启动cli
	if err := cliApp.Run(os.Args); err != nil {
		elog.ErrorCtx(context.Background(), "Failed to start application", elog.FieldError(err))
	}
}`)

}
