// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/main.got
// DO NOT EDIT!
package template

import "bytes"

func FromMain(projectName string, cmdList []string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package main

import (
	"os"`)
	buffer.WriteString("\n\"" + projectName + `/cmd"`)
	buffer.WriteString("\n\"" + projectName + `/common"

	"github.com/weblazy/easy/elog"
	"github.com/sunmi-OS/gocore/v2/utils"
	"github.com/urfave/cli/v2"
)

func main() {
	// 打印Banner
	utils.PrintBanner(common.ProjectName)
	// 配置cli参数
	app := cli.NewApp()
	app.Name = common.ProjectName
	app.Version = common.ProjectVersion

	// 指定命令运行的函数
	app.Commands = []*cli.Command{
        `)
	for _, cmd := range cmdList {
		buffer.WriteString(cmd)
	}
	buffer.WriteString(`
	}

	// 启动cli
	if err := app.Run(os.Args); err != nil {
		elog.ErrorCtx(context.Background(), "Failed to start application", elog.FieldError(err))
	}
}`)

}
