// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/model.got
// DO NOT EDIT!
package template

import (
	"bytes"
	"fmt"
	"strings"
)

func FromModel(dbName, tabels string, buffer *bytes.Buffer) {
	buffer.WriteString(`
package `)
	buffer.WriteString(dbName)
	buffer.WriteString(`

import (
	"fmt"

	"`)
	buffer.WriteString(easyConfig.Service.ProjectName)
	buffer.WriteString(fmt.Sprintf(`/conf"
	"gorm.io/gorm"
	"github.com/sunmi-OS/gocore/v2/db/orm"
	"github.com/weblazy/easy/econfig/eviper"
	"github.com/sunmi-OS/gocore/v2/utils"
)
const %sMysql = "%s"

func GetDB() *gorm.DB {
	return emysql.GetMysql(%sMysql).DB
}

func SchemaMigrate() {
	fmt.Println("开始初始化`, strings.Title(dbName), dbName, strings.Title(dbName)))
	buffer.WriteString(dbName)
	buffer.WriteString(`数据库")
	//自动建表，数据迁移
    `)
	buffer.WriteString(tabels)
	buffer.WriteString(`
	fmt.Println("数据库`)
	buffer.WriteString(dbName)
	buffer.WriteString(`初始化完成")
}`)

}
