// Code generated by hero.
// source: /Users/liuguoqiang/Desktop/go/mod/gocore/tools/gocore/template/api_routes.got
// DO NOT EDIT!
package template

import (
	"bytes"
	"fmt"
)

func FromRoutes(routesPkg, routes string, buffer *bytes.Buffer) {
	buffer.WriteString(fmt.Sprintf(`
package routes

import (
	"github.com/gin-gonic/gin"
	"net/http"
	_ "net/http/pprof"

	%s
)

func Routes(router *gin.Engine) {

	// 根目录健康检查
	router.Any("/", func(c *gin.Context) {
		c.String(http.StatusOK, "Welcome Easy Service")
	})
	%s
}
    `, routesPkg, routes))

}

func CreateInterceptor(homedir, handlerName string) string {
	return fmt.Sprintf(`package routes

import (
	"%s/http_config"

	"github.com/gin-gonic/gin"
)

func %sInterceptor(group *gin.RouterGroup) {

}
`, homedir, handlerName)
}
